name: flutter_practice
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_inappwebview: ^6.0.0
  flutter_linkify: ^6.0.0
  flutter_vap: ^1.1.0
  json_annotation: ^4.9.0
  oktoast: ^3.4.0
  share_plus: ^9.0.0
  time: ^2.1.4
  url_launcher: ^6.2.6
  video_player: ^2.9.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/webview/
    - assets/images/chat/
    - assets/images/
    - static/
